from .all_claims_reducer import all_claims_reducer
from .all_signals_reducer import merge_all_signals
from .contradictions_reducer import contradictions_reducer
from .info_symmetry_reducer import info_symmetry_reducer